/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "rcc_config.h"

void EXT_Init(void);
void GPIO_init(void);

int main(void)
{	Clock_config();
	GPIO_init();
	EXT_Init();

	while(1){


	}
}

void EXT_Init(void){

	//HABILITA AFIO CLOCK
	RCC->APB2ENR |= RCC_APB2ENR_AFIOEN;
	//PA0->EXT0
	AFIO->EXTICR[0] &=~(AFIO_EXTICR1_EXTI0);
	AFIO->EXTICR[0] |= AFIO_EXTICR1_EXTI0_PA;
	//NO ENMASCARAR EXTI0
	EXTI->IMR |= EXTI_IMR_MR0;
	//MODO FLANCO DE SUBIDA
	EXTI->RTSR |= EXTI_RTSR_RT0;
	EXTI->FTSR &=~(EXTI_FTSR_FT0);

	NVIC_SetPriority(EXTI0_IRQn,1);
	NVIC_EnableIRQ(EXTI0_IRQn);
}

void GPIO_init(void){

	//HABILITA CLOCK DEL PUERTO A
	RCC->APB2ENR |= RCC_APB2ENR_IOPAEN;
	//PA1->SALIDA PUSH PULL
	GPIOA->CRL &=~ (GPIO_CRL_CNF1 | GPIO_CRL_MODE1);
	GPIOA->CRL |= GPIO_CRL_MODE1;
	//PA0->ENTRADA
	GPIOA->CRL &=~ (GPIO_CRL_CNF0 | GPIO_CRL_MODE0);
	//MODO FLOATING INPUT
	GPIOA->CRL |= GPIO_CRL_CNF0_0;

}


void EXTI0_IRQHandler(void){

	NVIC_ClearPendingIRQ(EXTI0_IRQn);
	EXTI->PR |= EXTI_PR_PR0;
	GPIOA->ODR ^= GPIO_ODR_ODR1;

}
