/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "rcc_config.h"

void GPIO_init(void);
void SysTick_ClockConfig(uint32_t systick_valor);
void Delay_ms(uint32_t time);

int main(void)
{

	Clock_config();
	GPIO_init();
	//PARA 8MHz->1MILISEGUNDO
	SysTick_ClockConfig(8000);


	while(1){

		GPIOA->ODR ^= GPIO_ODR_ODR0;
		Delay_ms(1000);

	}
}

void GPIO_init(void){

	//HABILITA CLOCK DEL PUERTO A
	RCC->APB2ENR |= RCC_APB2ENR_IOPAEN;
	//PA0->SALIDA PUSH PULL
	GPIOA->CRL &=~ (GPIO_CRL_CNF0 | GPIO_CRL_MODE0);
	GPIOA->CRL |= GPIO_CRL_MODE0;

}

void SysTick_ClockConfig(uint32_t systick_valor){
	//LIMPIA REGISTRO CTRL
	SysTick->CTRL = 0;
	//CARGA EL VALOR A LOAD
	SysTick->LOAD = systick_valor-1;
	SysTick->VAL = 0;
	//HABILITAMOS CONTADOR Y FUENTE DE CLOCK->AHB
	SysTick->CTRL |=(SysTick_CTRL_ENABLE_Msk | SysTick_CTRL_CLKSOURCE_Msk);

}

void Delay_ms(uint32_t time){

	for (int i=0; i<time; i++){
		//ESPERA HASTA QUE LA BANDERA ESTE EN 1
		while(~SysTick->CTRL & SysTick_CTRL_COUNTFLAG_Msk);
		//LIMPIAMOS BANDERA
		SysTick->CTRL &= ~(SysTick_CTRL_COUNTFLAG_Msk);
	}

}


